### ISSUE TITLE
GPS doesn't get a fix

### ISSUE THREAD

**Issue by cmorlok** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#103]
GPS sometimes doesn't get a fix even when more than 10 satellites are in use. The issue has been introduced with the new M blobs.

**Comment by jaimemrjm** [comment]
I can confirm GPS needs several minutes to get location since the latest builds.

**Comment by cmorlok** [comment]
Can you provide a logcat? I had this problem only once and can't reproduce
any longer.

**Comment by jaimemrjm** [comment]
Please, find attached the [gps.log.zip](https://github.com/bq-dev/android_device_bq_piccolo/files/342128/gps.log.zip) from logcat. I have used [Sat sat](http://mvglasow.github.io/satstat) to check GPS status. I needs almost 3 minutes to get fix location. Note there's a SIGSEGV.

**Comment by cmorlok** [comment]
The tombstones (/data/tombstones/tombstone*) would be useful, if they still exist.

**Comment by jaimemrjm** [comment]
I cannot provide the files, because I have this ROM no more.

**Comment by DerSaxxe** [comment]
Same here with the latest build 
[tmp_7715-logfiles-2065457878.zip](https://github.com/bq-dev/android_device_bq_piccolo/files/355718/tmp_7715-logfiles-2065457878.zip)
[tmp_7715-tombstones1737011934.zip](https://github.com/bq-dev/android_device_bq_piccolo/files/355719/tmp_7715-tombstones1737011934.zip)

**Comment by Kra1o5** [comment]
I will try to fix it for next release (weekend build).

**Comment by 1tft** [comment]
I can confirm GPS needs several minutes to get location tested with latest build:
Version: RC [2016/07/31]
Firmwarebase: 4.1.0 (Android 6.0.1)
Installation/Upgrade: no upgrade, full clean installation with a factory reset prior installation

On second phone I get fix within seconds.
Reference build on second phone: 2016/05/18
Firmwarebase: 3.2.9 (Android 5.1.1)

**Comment by jaimemrjm** [comment]
The issue is fixed. Tested with the latest build from 2016 december.

**Comment by cmorlok** [comment]
No, it's not fixed. I just happens only when under certain conditions.
