### ISSUE TITLE
Proximity sensor remains active in lock screen

### ISSUE THREAD

**Issue by pipa89** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#122]
When you unlock the screen, the proximity sensor remains active until you unlock the lock screen is unnecessary, though not a fatal error.

**Comment by cmorlok** [comment]
I have seen some commits on gerrit. Is this fixed in the 20161018 build?

**Comment by Migui2356** [comment]
Yeah it is also fixed!

**Comment by Migui2356** [comment]
Edit: It isn't fixed, I though it was but it isn't, sorry for the bad information!
